theme: jekyll-theme-midnight

baseurl: /shiuli

title: Shiuli
description: A simple configurable landing page for REST APIs.

author: Indra Basak

logo: ./images/shiuli-title.png
docs: https://github.com/indrabasak/shiuli/wiki
blog: https://indrabasak.github.io