theme: jekyll-theme-midnight

title: Shiuli
description: A simple configurable landing page for REST APIs.
author: Indra Basak

baseurl: /shiuli

logo: ./images/shiuli-logo_40px.png
blog: https://indrabasak.github.io

  
