title: Shiuli
description: A simple configurable landing page for REST APIs.
author: Indra Basak

theme: jekyll-theme-midnight

baseurl: /shiuli

navbar-links:
  logo: ./images/shiuli-title.png
  blog: https://indrabasak.github.io
