theme: jekyll-theme-cayman

title: Shiuli
description: A simple configurable landing page for REST APIs.
author: Indra Basak

baseurl: /shiuli

logo: ./images/shiuli-title.png
blog: https://indrabasak.github.io
